rules:
- source: client1
  destination: client2
  commands:
    - test
- source: agent1
  destination: memory
  commands:
    - memory.*
- source: daemon
  destination: "*"
  commands:
    - version
- source: "*"
  destination: daemon
  commands:
    - version
