#!/usr/bin/env python3
"""Generate sandbox package Go files with correct formatting."""
import os

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "internal", "sandbox")
os.makedirs(BASE, exist_ok=True)

# spec.go
with open(os.path.join(BASE, "spec.go"), "w") as f:
    f.write('package sandbox\n')
    f.write('\n')
    f.write('import (\n')
    f.write('\t"fmt"\n')
    f.write('\t"net"\n')
    f.write('\t"path/filepath"\n')
    f.write('\t"regexp"\n')
    f.write('\t"time"\n')
    f.write(')\n')
    f.write('\n')
    f.write('// SandboxState represents the lifecycle state of a sandbox.\n')
    f.write('type SandboxState string\n')
    f.write('\n')
    f.write('const (\n')
    f.write('\tStateCreated SandboxState = "created"\n')
    f.write('\tStateRunning SandboxState = "running"\n')
    f.write('\tStateStopped SandboxState = "stopped"\n')
    f.write('\tStateError   SandboxState = "error"\n')
    f.write(')\n')
    f.write('\n')
    f.write('// Resources defines resource limits for a sandbox microVM.\n')
    f.write('type Resources struct {\n')
    f.write('\tVCPUs    int64 `json:"vcpus"`\n')
    f.write('\tMemoryMB int64 `json:"memory_mb"`\n')
    f.write('}\n')
    f.write('\n')
    f.write('// NetworkPolicy defines network access rules for a sandbox.\n')
    f.write('// DefaultDeny must always be true; allowed entries selectively open access.\n')
    f.write('type NetworkPolicy struct {\n')
    f.write('\tDefaultDeny      bool     `json:"default_deny"`\n')
    f.write('\tAllowedHosts     []string `json:"allowed_hosts,omitempty"`\n')
    f.write('\tAllowedPorts     []uint16 `json:"allowed_ports,omitempty"`\n')
    f.write('\tAllowedProtocols []string `json:"allowed_protocols,omitempty"`\n')
    f.write('}\n')
    f.write('\n')
    f.write('// SandboxSpec defines the desired state of a Firecracker sandbox.\n')
    f.write('type SandboxSpec struct {\n')
    f.write('\tID            string        `json:"id"`\n')
    f.write('\tName          string        `json:"name"`\n')
    f.write('\tResources     Resources     `json:"resources"`\n')
    f.write('\tNetworkPolicy NetworkPolicy `json:"network_policy"`\n')
    f.write('\tVsockCID      uint32        `json:"vsock_cid"`\n')
    f.write('\tRootfsPath    string        `json:"rootfs_path"`\n')
    f.write('\tKernelPath    string        `json:"kernel_path,omitempty"`\n')
    f.write('\tWorkspaceMB   int           `json:"workspace_mb"`\n')
    f.write('}\n')
    f.write('\n')
    f.write('// SandboxInfo captures the runtime state of a sandbox.\n')
    f.write('type SandboxInfo struct {\n')
    f.write('\tSpec       SandboxSpec  `json:"spec"`\n')
    f.write('\tState      SandboxState `json:"state"`\n')
    f.write('\tPID        int          `json:"pid,omitempty"`\n')
    f.write('\tStartedAt  *time.Time   `json:"started_at,omitempty"`\n')
    f.write('\tStoppedAt  *time.Time   `json:"stopped_at,omitempty"`\n')
    f.write('\tError      string       `json:"error,omitempty"`\n')
    f.write('\tSocketPath string       `json:"socket_path,omitempty"`\n')
    f.write('\tTapDevice  string       `json:"tap_device,omitempty"`\n')
    f.write('\tHostIP     string       `json:"host_ip,omitempty"`\n')
    f.write('\tGuestIP    string       `json:"guest_ip,omitempty"`\n')
    f.write('}\n')
    f.write('\n')
    f.write('var nameRegex = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9._-]{0,62}$`)\n')
    f.write('\n')
    f.write('// Validate checks that the SandboxSpec has all required fields with safe values.\n')
    f.write('func (s *SandboxSpec) Validate() error {\n')
    f.write('\tif s.ID == "" {\n')
    f.write('\t\treturn fmt.Errorf("sandbox ID is required")\n')
    f.write('\t}\n')
    f.write('\tif s.Name == "" {\n')
    f.write('\t\treturn fmt.Errorf("sandbox name is required")\n')
    f.write('\t}\n')
    f.write('\tif !nameRegex.MatchString(s.Name) {\n')
    f.write('\t\treturn fmt.Errorf("sandbox name must match pattern %s, got %q", nameRegex.String(), s.Name)\n')
    f.write('\t}\n')
    f.write('\tif s.Resources.VCPUs < 1 || s.Resources.VCPUs > 32 {\n')
    f.write('\t\treturn fmt.Errorf("VCPUs must be between 1 and 32, got %d", s.Resources.VCPUs)\n')
    f.write('\t}\n')
    f.write('\tif s.Resources.MemoryMB < 128 || s.Resources.MemoryMB > 32768 {\n')
    f.write('\t\treturn fmt.Errorf("memory must be between 128 and 32768 MB, got %d", s.Resources.MemoryMB)\n')
    f.write('\t}\n')
    f.write('\tif s.VsockCID < 3 {\n')
    f.write('\t\treturn fmt.Errorf("vsock CID must be >= 3 (0=hypervisor, 1=loopback, 2=host), got %d", s.VsockCID)\n')
    f.write('\t}\n')
    f.write('\tif s.RootfsPath == "" {\n')
    f.write('\t\treturn fmt.Errorf("rootfs path is required")\n')
    f.write('\t}\n')
    f.write('\tif !filepath.IsAbs(s.RootfsPath) {\n')
    f.write('\t\treturn fmt.Errorf("rootfs path must be absolute, got %q", s.RootfsPath)\n')
    f.write('\t}\n')
    f.write('\tif s.KernelPath != "" && !filepath.IsAbs(s.KernelPath) {\n')
    f.write('\t\treturn fmt.Errorf("kernel path must be absolute, got %q", s.KernelPath)\n')
    f.write('\t}\n')
    f.write('\tif !s.NetworkPolicy.DefaultDeny {\n')
    f.write('\t\treturn fmt.Errorf("network policy default_deny must be true")\n')
    f.write('\t}\n')
    f.write('\tif err := validateNetworkPolicy(&s.NetworkPolicy); err != nil {\n')
    f.write('\t\treturn fmt.Errorf("invalid network policy: %w", err)\n')
    f.write('\t}\n')
    f.write('\treturn nil\n')
    f.write('}\n')
    f.write('\n')
    f.write('func validateNetworkPolicy(np *NetworkPolicy) error {\n')
    f.write('\tfor _, host := range np.AllowedHosts {\n')
    f.write('\t\tif net.ParseIP(host) == nil {\n')
    f.write('\t\t\tif _, _, err := net.ParseCIDR(host); err != nil {\n')
    f.write('\t\t\t\treturn fmt.Errorf("invalid allowed host (must be IP or CIDR): %q", host)\n')
    f.write('\t\t\t}\n')
    f.write('\t\t}\n')
    f.write('\t}\n')
    f.write('\tfor _, proto := range np.AllowedProtocols {\n')
    f.write('\t\tswitch proto {\n')
    f.write('\t\tcase "tcp", "udp", "icmp":\n')
    f.write('\t\tdefault:\n')
    f.write('\t\t\treturn fmt.Errorf("unsupported protocol %q (allowed: tcp, udp, icmp)", proto)\n')
    f.write('\t\t}\n')
    f.write('\t}\n')
    f.write('\treturn nil\n')
    f.write('}\n')
    f.write('\n')
    f.write('// RuntimeConfig holds paths and settings for the Firecracker runtime.\n')
    f.write('type RuntimeConfig struct {\n')
    f.write('\tFirecrackerBin string `json:"firecracker_bin"`\n')
    f.write('\tJailerBin      string `json:"jailer_bin"`\n')
    f.write('\tKernelImage    string `json:"kernel_image"`\n')
    f.write('\tRootfsTemplate string `json:"rootfs_template"`\n')
    f.write('\tChrootBaseDir  string `json:"chroot_base_dir"`\n')
    f.write('\tStateDir       string `json:"state_dir"`\n')
    f.write('}\n')
    f.write('\n')
    f.write('// Validate checks that runtime paths are absolute.\n')
    f.write('func (c *RuntimeConfig) Validate() error {\n')
    f.write('\tchecks := map[string]string{\n')
    f.write('\t\t"firecracker_bin": c.FirecrackerBin,\n')
    f.write('\t\t"jailer_bin":      c.JailerBin,\n')
    f.write('\t\t"rootfs_template": c.RootfsTemplate,\n')
    f.write('\t\t"chroot_base_dir": c.ChrootBaseDir,\n')
    f.write('\t\t"state_dir":       c.StateDir,\n')
    f.write('\t}\n')
    f.write('\tfor name, path := range checks {\n')
    f.write('\t\tif path == "" {\n')
    f.write('\t\t\treturn fmt.Errorf("%s is required", name)\n')
    f.write('\t\t}\n')
    f.write('\t\tif !filepath.IsAbs(path) {\n')
    f.write('\t\t\treturn fmt.Errorf("%s must be an absolute path, got %q", name, path)\n')
    f.write('\t\t}\n')
    f.write('\t}\n')
    f.write('\treturn nil\n')
    f.write('}\n')

print("spec.go written")

# manager.go
with open(os.path.join(BASE, "manager.go"), "w") as f:
    f.write('package sandbox\n')
    f.write('\n')
    f.write('import "context"\n')
    f.write('\n')
    f.write('// SandboxManager defines the lifecycle interface for managing Firecracker sandboxes.\n')
    f.write('// All implementations must ensure that every operation is signed and logged\n')
    f.write('// through the kernel before side-effects occur.\n')
    f.write('type SandboxManager interface {\n')
    f.write('\t// Create provisions a new sandbox from the given spec without starting it.\n')
    f.write('\tCreate(ctx context.Context, spec SandboxSpec) error\n')
    f.write('\n')
    f.write('\t// Start boots a previously created sandbox\'s Firecracker microVM.\n')
    f.write('\tStart(ctx context.Context, id string) error\n')
    f.write('\n')
    f.write('\t// Stop gracefully shuts down a running sandbox\'s microVM.\n')
    f.write('\tStop(ctx context.Context, id string) error\n')
    f.write('\n')
    f.write('\t// Delete removes a stopped sandbox and cleans up all its resources.\n')
    f.write('\tDelete(ctx context.Context, id string) error\n')
    f.write('\n')
    f.write('\t// List returns info for all known sandboxes regardless of state.\n')
    f.write('\tList(ctx context.Context) ([]SandboxInfo, error)\n')
    f.write('\n')
    f.write('\t// Status returns the current info for a single sandbox.\n')
    f.write('\tStatus(ctx context.Context, id string) (*SandboxInfo, error)\n')
    f.write('}\n')

print("manager.go written")
